### ISSUE TITLE
Getting Error while importing 

### ISSUE THREAD

**Issue by MuzzamilDev** [tepikin/AndroidBooksReader#1]
Cannot read packageName from /Users/muzzamil/Documents/New Pdf Sample/AndroidBooksReader/app/..\submodule_LibreraReader\EBookaPDF\AndroidManifest.xml

**Comment by tepikin** [comment]
You have copied not the all repository.
I think that your "submodule_LibreraReader" folder is empty.
For copy the entire repository with submodules clone repository recursively:
 `git clone `**`--recursive`**` "https://github.com/tepikin/AndroidBooksReader.git"`

If this does not help, just copy the project source code from this link https://yadi.sk/d/MuKYKI0iL9BeqQ

**Comment by Ramkesh9** [comment]
i tried to import your project but its giving a error like :

A problem occurred configuring project ':app'.
> Cannot read packageName from /Users/ricky/Downloads/AndroidBooksReader/app/..\submodule_LibreraReader\EBookaPDF\AndroidManifest.xml

**Comment by Ramkesh9** [comment]
This link https://yadi.sk/d/MuKYKI0iL9BeqQ  downloaded 1 gb code , 
Still giving same error, My Bad.
